### ISSUE TITLE
Can see strapi-plugin-apollo-sandbox

### ISSUE THREAD

**Issue by tuan-zigvy** [creazy231/strapi-plugin-apollo-sandbox#1]
`middlewares.ts
export default [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        directives: {
          "frame-src": [
            "http://localhost:*",
            "self",
            "sandbox.embed.apollographql.com",
          ],
        },
      },
    },
  },
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];

PULGIN.TS
export default {
  graphql: {
    enabled: true,
    config: {
      // endpoint: "/graphql",
      // shadowCRUD: true,
      playgroundAlways: false,
      // depthLimit: 7,
      // amountLimit: 100,
      // apolloServer: {
      //   tracing: false,
      // },
    },
    "apollo-sandbox": {
      // enables the plugin only in development mode
      // if you also want to use it in production, set this to true
      // keep in mind that graphql playground has to be enabled
      enabled: process.env.NODE_ENV === "production" ? false : true, // OPTIONAL - endpoint has to be accessible from the browser
    },
  },
};

package.json
dependencies": {
    "@apollo/server": "^4.9.0",
    "@creazy231/strapi-plugin-apollo-sandbox": "^0.0.11",
    "@strapi/plugin-graphql": "4.12.1",
    "@strapi/plugin-i18n": "4.12.1",
    "@strapi/plugin-users-permissions": "4.12.1",
    "@strapi/strapi": "^4.12.4",
    "graphql-scalars": "^1.22.2",
    "pg": "8.8.0"
  },
`

i can see [strapi-plugin-apollo-sandbox](https://github.com/creazy231/strapi-plugin-apollo-sandbox)

**Comment by creazy231** [comment]
I guess you want to say that you can't see the plugin in your admin panel, right?
Did you run `npm run build` or `yarn build` after going through the documentation?

**Comment by tuan-zigvy** [comment]
yes i can not see any thing 
i already run yarn build  , yarn develop

**Comment by creazy231** [comment]
Would you be able to share a project / reproduction where the problem appears so I can try to reproduce the problem?

**Comment by tuan-zigvy** [comment]
> Would you be able to share a project / reproduction where the problem appears so I can try to reproduce the problem?

https://github.com/tuan-zigvy/test 

thank you

**Comment by creazy231** [comment]
Can you try to edit your `config/plugins.ts` to the following:

```
export default {
  graphql: {
    enabled: true,
    config: {
      endpoint: "/graphql",
      shadowCRUD: true,
      playgroundAlways: false,
      depthLimit: 7,
      amountLimit: 100,
      apolloServer: {
        tracing: false,
      },
    },
  },
  "apollo-sandbox": {
    // enables the plugin only in development mode
    // if you also want to use it in production, set this to true
    // keep in mind that graphql playground has to be enabled
    enabled: process.env.NODE_ENV === "production" ? false : true,
    endpoint: "https://tunneled-strapi.com/graphql", // OPTIONAL - endpoint has to be accessible from the browser
  },
};
```

**Comment by tuan-zigvy** [comment]
> 

![image](https://github.com/creazy231/strapi-plugin-apollo-sandbox/assets/139092565/ea204b53-a184-4295-811c-dbe1769e0c2a)
I still don't see anything

**Comment by creazy231** [comment]
Ok, will clone your repo and try to reproduce. Give me some minutes

**Comment by creazy231** [comment]
@tuan-zigvy some things you have to change on your setup.

1. Please make sure using latest version of Strapi and its plugins.
```
// package.json
"@strapi/plugin-graphql": "4.12.4",
```

2. Your scripts just don't make that much sense but if you want to keep them for whatever reason, you have to make these changes:
```
"scripts": {
  "local": "strapi develop",
  "start": "strapi start",
  "build": "strapi build",
  "strapi": "strapi",
  "dev": "yarn build && yarn local",
  "prod": "yarn build && yarn start"
},
```

then you can start developing with `yarn dev`

---

> **Important**
> This plugins is made to work in development mode only since the default graphql playground is required and is not exposed by default in production. With the above settings it should work, but running `yarn start` or `yarn prod` strapi runs in production mode which automatically disables the **strapi-plugin-apollo-sandbox** plugin.

---

Please give these changes a try and let me know if it works :)

**Comment by tuan-zigvy** [comment]
>i update latest version so it work , thank you

**Comment by creazy231** [comment]
Awesome 🙌
