### ISSUE TITLE
Unable to reach server

### ISSUE THREAD

**Issue by rweisse** [creazy231/strapi-plugin-apollo-sandbox#2]
Hi,

I have installed the plugin as described. However, I get the following error message: "Unable to reach server"

![image](https://github.com/creazy231/strapi-plugin-apollo-sandbox/assets/7416092/8436a057-eaba-43c0-9e6a-b9cefdede273)

I was forced to install your plugin via the additional parameter `--force`, because of the conflicting peer dependency: styled-components@5.3.11.:  `npm install @creazy231/strapi-plugin-apollo-sandbox --save --force`
Apart from that, the installation went without any problems.

### Config files
```ts
// config/middlewares.ts
export default [
  'strapi::errors',
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        directives: {
          "frame-src": [ "http://localhost:*", "self", "sandbox.embed.apollographql.com" ],
        },
      },
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
```

```ts
// config/plugins.ts
export default {
  "graphql": {
    enabled: true,
    config: {
      // set this to true if you want to enable the playground in production
      playgroundAlways: false,
    },
  },
  "apollo-sandbox": {
    // enables the plugin only in development mode
    // if you also want to use it in production, set this to true
    // keep in mind that graphql playground has to be enabled
    enabled: process.env.NODE_ENV === "production" ? false : true,
    // endpoint: "https://tunneled-strapi.com/graphql", // OPTIONAL - endpoint has to be accessible from the browser
  },
};
```
```json
{
  "name": "website-strapi-backend",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@creazy231/strapi-plugin-apollo-sandbox": "^0.0.11",
    "@strapi/plugin-graphql": "^4.12.6",
    "@strapi/plugin-i18n": "4.12.6",
    "@strapi/plugin-users-permissions": "4.12.6",
    "@strapi/strapi": "4.12.6",
    "mysql": "2.18.1"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "27d2a873-9ea2-40db-ac02-862366141a86"
  },
  "engines": {
    "node": ">=16.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```
### Environment
- Node.js v18.16.0
- Strapi v4.12.6

**Comment by creazy231** [comment]
Thanks for your report. I'll take a closer look into this soon and will also update dependencies.
Are there any errors in the console or network tab of your browser relating to this plugin or `*.lt.boltapi.com`?

**Comment by creazy231** [comment]
Guess I know the problem and I guess I'll have to mention an additional thing in the README.

You can disable the header at all which could lead into permission issues requesting data, or:

Please go to `Strapi > Settings > API Tokens > Create new API Token` and create a new Token with full access and unlimited duration.
Then go to the Apollo Sandbox Plugin and insert the token you've created there.

![image](https://github.com/creazy231/strapi-plugin-apollo-sandbox/assets/13473174/7fa0a49c-cc3e-4870-8ef5-a2bd526d231f)

**Comment by rweisse** [comment]
Thank you for your fast reply. I did what you suggested. Unfortunately it did not work. I don't think the error has anything to do with the token. Apollo sandbox does not reach the GraphQL backend at all.
In your screenshot the schema is displayed. In my case, however, the schema is missing. Only an `ExampleQuery` is listed. But I have not configured it in Strapi. It is only a placeholder because the actual GraphQL backend cannot be reached. However I reach the Playground via http://localhost:1337/graphql without any problems. The schema is also listed correctly there.

![image](https://github.com/creazy231/strapi-plugin-apollo-sandbox/assets/7416092/7a5e0504-4fed-4260-acb3-14750169e07f)

--
### EDIT: I have added the Auth-Token in the connection settings now - but it still doesn't work. I didn't understand until now why a different endpoint URL is always generated. Why is the localhost not listed there?

![image](https://github.com/creazy231/strapi-plugin-apollo-sandbox/assets/7416092/c9c5666d-1108-445a-9a7d-57187067ad29)

**Comment by creazy231** [comment]
Does it work when you disable the check for the Authorization Header? So not sending the Token at all?
The generated endpoint is to apollo sandbox be able to reach your local graphql server. If you'd use localhost, the sandbox can't connect to it since - as it says - it's a sandbox not running by Strapi itself. Therefore you need to tunnel the graphql endpoint.

Tipp: The Authorization Header is only needed when you want to access data which is not expoed to the `public` role in Strapi.

**Comment by creazy231** [comment]
Could you please try to open the generated Endpoint in an other window? For example in your posted case: `https://cold-bear-71.it.boltapi.com/graphql`. That endpoint should show the same as `http://localhost:1337/graphql` would show.

Btw: Wondering, that `localhost` works for you at all since I only face problems accessing `localhost` using Node v18 and therefore switched to `127.0.0.1` instead. Maybe this could also be the reason. Could you give it a try? In this case I have to edit the plugin to expose `localhost` if the user uses `localhost` instead of `127.0.0.1` :)

**Comment by rweisse** [comment]
> The generated endpoint is to apollo sandbox be able to reach your local graphql server. If you'd use localhost, the sandbox can't connect to it since - as it says - it's a sandbox not running by Strapi itself. Therefore you need to tunnel the graphql endpoint.

Ok, now some things have become clear to me. I checked everything again - but this time with a different internet access point. Everything worked great this time. It turned out that the routers firewall blocked the tunnel.

> Btw: Wondering, that localhost works for you at all since I only face problems accessing localhost using Node v18 and therefore switched to 127.0.0.1 instead.

There was no difference between localhost and 127.0.0.1. Both worked for me in the end.

Thank you very much for your help! It turned out that it was our firewall and not your plugin. I apologize for the confusion.

**Comment by creazy231** [comment]
Nice to hear :) and no worries at all about the confusion - I'm just happy you were able to get the plugin up and running in the end. Thank you for circling back and letting me know, and for taking the time to troubleshoot on your end. I really appreciate you following up, and I'm thankful we were able to resolve this.
