### ISSUE TITLE
./config/middlewares.ts file doesnt exist 

### ISSUE THREAD

**Issue by jees47** [creazy231/strapi-plugin-apollo-sandbox#7]
I couldn't find the file on my project.  I tried to create the file and do the following on the project but it doesn't work.

{
  "name": "form-app",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-cloud": "4.15.4",
    "@strapi/plugin-graphql": "^4.15.4",
    "@strapi/plugin-i18n": "4.15.4",
    "@strapi/plugin-users-permissions": "4.15.4",
    "@strapi/strapi": "4.15.4",
    "better-sqlite3": "8.6.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "26011d83-73a8-44cb-b01a-3debba17f030"
  },
  "engines": {
    "node": ">=18.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

this is my configuration.

**Comment by creazy231** [comment]
You can't just create the file without any content. Please fill it with content from the README
