### ISSUE TITLE
Support Node 20.x LTS

### ISSUE THREAD

**Issue by Alex4386** [creazy231/strapi-plugin-apollo-sandbox#8]
## How to reproduce
1. Install Latest node LTS (20.x)
2. Install strapi
3. Run `yarn add @creazy231/strapi-plugin-apollo-sandbox`
4. ```
   error @creazy231/strapi-plugin-apollo-sandbox@0.0.13: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "20.10.0"
   error Found incompatible module.
   info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
   ```


## Extra
If there is reason why It can't be supported (e.g. Breaking change in Node 19+), Could you give me the insight of it so I can create a PR for it?

**Comment by ahathaway** [comment]
@Alex4386 @creazy231 
I am using this with node 20.11.0 without issue, it seems like perhaps a simple PR updating the package.json manifest could resolve this yeah?

**Comment by mathiasverraes** [comment]
The issue still exists with the latest versions of strapi and this plugin.

**Comment by creazy231** [comment]
will test and release a new version of this plugin early next week. Thanks for reporting, wasn't aware of since I don't use it in current projects.

**Comment by creazy231** [comment]
this should be fixed with https://github.com/creazy231/strapi-plugin-apollo-sandbox/releases/tag/v0.0.15
