### ISSUE TITLE
Please upgrade to support Stratpi v5.0.0 beta. 2

### ISSUE THREAD

**Issue by eugle** [creazy231/strapi-plugin-apollo-sandbox#9]
I have tried the Strati v5 beta version and cannot install @ creazy231/Strati plugin Apollo sandbox. Please upgrade it to support the latest version. Thank you

**Comment by creazy231** [comment]
Will look into this once Strapi v5 got its first stable release

**Comment by makoneth** [comment]
Strapi 5 it's available

**Comment by creazy231** [comment]
for any update about the Strapi v5 migration look at this issue please: https://github.com/creazy231/strapi-plugin-apollo-sandbox/issues/12
